- name: Deploy Docker Container on Localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Ensure Docker is Installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - n- name: Pull latest Docker image
      community.docker.docker_image:
        name: asingh2112/calculator
        tag: latest
        source: pull
        force_source: yes
        force_tag: yes


    - name: Stop and remove existing container (if running)
      community.docker.docker_container:
        name: calculator
        state: absent
        force_kill: yes

    - name: Run the new container
      community.docker.docker_container:
        name: calculator
        image: asingh2112/calculator:latest
        state: started
        restart_policy: always
        ports:
          - "9090:8080"
        interactive: yes
        tty: yes
